[package]
name = "bytecode"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.43", features = ["derive"] }
clio = "0.3.5"
env_logger = "0.11.8"
log = "0.4.27"
